package game

import "fmt"

// showRules 显示游戏规则
func (g *Game) showRules() {
	g.clearScreen()
	fmt.Println("=== 二十一点游戏规则 ===")
	fmt.Println()
	fmt.Println("🎯 游戏目标:")
	fmt.Println("   让手中牌的点数尽可能接近21点，但不能超过21点")
	fmt.Println("   点数比庄家更接近21点就获胜")
	fmt.Println()
	fmt.Println("🃏 牌面点数:")
	fmt.Println("   • 数字牌(2-10): 按牌面数字计算")
	fmt.Println("   • 花牌(J,Q,K): 每张都是10点")
	fmt.Println("   • A: 可以是1点或11点(自动选择最优)")
	fmt.Println()
	fmt.Println("💰 下注系统:")
	fmt.Println("   • 初始筹码: 1000")
	fmt.Println("   • 下注选项: 10, 25, 50, 100, 200 筹码")
	fmt.Println("   • 筹码不足时可选择全押")
	fmt.Println("   • 普通获胜: 1:1 赔率")
	fmt.Println("   • Blackjack获胜: 3:2 赔率(非加倍)")
	fmt.Println("   • 平局: 返还下注金额")
	fmt.Println("   • 筹码用完可选择重新开始")
	fmt.Println()
	fmt.Println("🎮 游戏流程:")
	fmt.Println("   1. 选择下注金额(从预设选项中选择)")
	fmt.Println("   2. 玩家和庄家各发2张牌")
	fmt.Println("   3. 玩家选择要牌(h)、停牌(s)或加倍(d)")
	fmt.Println("   4. 庄家小于17点必须要牌，17点以上必须停牌")
	fmt.Println("   5. 比较点数决定胜负并结算筹码")
	fmt.Println()
	fmt.Println("🎮 操作命令:")
	fmt.Println("   • h/hit: 要牌")
	fmt.Println("   • s/stand: 停牌")
	fmt.Println("   • d/double/doubledown: 加倍(仅前两张牌时可用)")
	fmt.Println("   • q/quit: 退出游戏")
	fmt.Println()
	fmt.Println("⚡ 加倍功能:")
	fmt.Println("   • 只能在拿到前两张牌时使用")
	fmt.Println("   • 下注金额翻倍，需要足够筹码")
	fmt.Println("   • 加倍后只能再拿一张牌，然后必须停牌")
	fmt.Println("   • 加倍后的Blackjack按1:1赔率计算")
	fmt.Println()
	fmt.Println("🏆 特殊情况:")
	fmt.Println("   • Blackjack: 前两张牌就是21点(A+10点牌)")
	fmt.Println("   • 爆牌: 点数超过21点立即失败")
	fmt.Println("   • 平局: 双方点数相同")
	fmt.Println()
	fmt.Print("按回车键继续...")
	g.Scanner.Scan()
}
